@ECHO OFF

SET BASE_DIR=%~dp0
SET BASE_DIR=%BASE_DIR:~0,-1%

cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_MODULES=false -DBUILD_GENERIC_CONTAINER=false -DBUILD_POSIX=false %BASE_DIR%/../../memoria