FROM ubuntu:24.04

RUN echo "Install dependencies" && apt-get update  -y; apt install software-properties-common -y
RUN add-apt-repository ppa:ubuntu-toolchain-r/test -y; apt update -y
RUN apt-get install -y wget git mc curl zip unzip tar pkg-config gcc-14 g++-14 build-essential linux-headers-$(uname -r)  make autoconf libtool automake autoconf-archive ninja-build cmake gnutls-dev lksctp-tools libsctp-dev ragel valgrind doxygen xfsprogs xfslibs-dev libc-ares-dev libfmt-dev libyaml-cpp-dev protobuf-compiler
RUN apt-get install -y libboost-all-dev 
RUN apt-get install -y clang-19 libclang-19-dev
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 14 --slave /usr/bin/g++ g++ /usr/bin/g++-14
RUN update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
RUN update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
RUN update-alternatives --set c++ /usr/bin/g++
RUN update-alternatives --set cc /usr/bin/gcc
